ALTER TABLE "Gift" ADD COLUMN "brand" TEXT;
ALTER TABLE "Gift" ADD COLUMN "team" TEXT;
ALTER TABLE "Gift" ADD COLUMN "sport" TEXT;
ALTER TABLE "Gift" ADD COLUMN "country" TEXT;
ALTER TABLE "Gift" ADD COLUMN "licenseStatus" TEXT NOT NULL DEFAULT 'ORIGINAL_FAN';
ALTER TABLE "Gift" ADD COLUMN "licenseExpiry" DATETIME;
ALTER TABLE "Gift" ADD COLUMN "assetSource" TEXT;
ALTER TABLE "LiveBattle" ADD COLUMN "giftTotalAKobo" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "LiveBattle" ADD COLUMN "giftTotalBKobo" INTEGER NOT NULL DEFAULT 0;
